
import Footer from "components/footer/footer"
import Header from "components/header/header"
import "bootstrap/dist/css/bootstrap.min.css";
import '../globals.css'
import  './auth.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
<Header/>

        {children}
        <Footer/>
        </body>
    </html>
  )
}
